<a href="https://colab.research.google.com/github/sunilchaurha/python-learning/blob/main/Panda-1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
data = pd.read_csv("/content/data.csv")
data.head

<bound method NDFrame.head of            id diagnosis  ...  symmetry_worst  fractal_dimension_worst
0      842302         M  ...          0.4601                  0.11890
1      842517         M  ...          0.2750                  0.08902
2    84300903         M  ...          0.3613                  0.08758
3    84348301         M  ...          0.6638                  0.17300
4    84358402         M  ...          0.2364                  0.07678
..        ...       ...  ...             ...                      ...
564    926424         M  ...          0.2060                  0.07115
565    926682         M  ...          0.2572                  0.06637
566    926954         M  ...          0.2218                  0.07820
567    927241         M  ...          0.4087                  0.12400
568     92751         B  ...          0.2871                  0.07039

[569 rows x 32 columns]>

In [7]:
filter=["id","diagnosis","radius_mean","texture_mean","perimeter_mean","area_mean","smoothness_mean","compactness_mean"]
filteredData = data[filter]
filteredData.head()

         id diagnosis  ...  smoothness_mean  compactness_mean
0    842302         M  ...          0.11840           0.27760
1    842517         M  ...          0.08474           0.07864
2  84300903         M  ...          0.10960           0.15990
3  84348301         M  ...          0.14250           0.28390
4  84358402         M  ...          0.10030           0.13280

[5 rows x 8 columns]

In [9]:
filteredData.sort_index(axis=1, ascending=True)

     area_mean  compactness_mean  ... smoothness_mean  texture_mean
0       1001.0           0.27760  ...         0.11840         10.38
1       1326.0           0.07864  ...         0.08474         17.77
2       1203.0           0.15990  ...         0.10960         21.25
3        386.1           0.28390  ...         0.14250         20.38
4       1297.0           0.13280  ...         0.10030         14.34
..         ...               ...  ...             ...           ...
564     1479.0           0.11590  ...         0.11100         22.39
565     1261.0           0.10340  ...         0.09780         28.25
566      858.1           0.10230  ...         0.08455         28.08
567     1265.0           0.27700  ...         0.11780         29.33
568      181.0           0.04362  ...         0.05263         24.54

[569 rows x 8 columns]

In [10]:
filteredData.sort_values(by="id", ascending=True)

            id diagnosis  ...  smoothness_mean  compactness_mean
131       8670         M  ...          0.10920           0.12230
287       8913         B  ...          0.06955           0.03729
291       8915         B  ...          0.08992           0.09823
403       9047         B  ...          0.09879           0.08836
47       85715         M  ...          0.11580           0.12310
..         ...       ...  ...              ...               ...
449  911157302         M  ...          0.09684           0.11750
460  911296201         M  ...          0.09898           0.11100
461  911296202         M  ...          0.10840           0.19880
463  911320501         B  ...          0.08508           0.05855
464  911320502         B  ...          0.07466           0.05994

[569 rows x 8 columns]

# New Section